// Generate a context brief that can be pasted into any AI session
// This is Solis Memoria completing itself — the graph writes back
import { openGraph } from "./graph/schema.js";
import fs from "fs";

const db = openGraph();

// 1. Who you are
const identity = db.prepare(`
  SELECT term, COUNT(DISTINCT convo_id) as convos
  FROM convo_terms
  WHERE term IN ('codex vivus','codex machina','iron vein','solis memoria','myth tech',
                 'justin oberg','justin paul','paul berg','clark county','salmon creek',
                 'pacific northwest','columbia river','promethea','sovereign','recursive','flame')
  GROUP BY term ORDER BY convos DESC
`).all() as any[];

// 2. What you're working on (most recent S-tier with build signals)
const recentBuilds = db.prepare(`
  SELECT title, created_at, total_words, category, preview
  FROM conversations
  WHERE has_build = 1 AND score_tier = 'S'
  AND created_at > unixepoch() - 90*86400
  ORDER BY created_at DESC LIMIT 10
`).all() as any[];

// 3. Open decisions (recent decision-signal convos)
const recentDecisions = db.prepare(`
  SELECT title, created_at, category, preview
  FROM conversations
  WHERE has_decision = 1 AND score_tier IN ('S','A')
  AND created_at > unixepoch() - 60*86400
  ORDER BY created_at DESC LIMIT 5
`).all() as any[];

// 4. Deepest threads (topics spanning most months)
const threads = db.prepare(`
  SELECT term, COUNT(DISTINCT substr(datetime(c.created_at, 'unixepoch'), 1, 7)) as months,
         COUNT(DISTINCT t.convo_id) as convos
  FROM convo_terms t
  JOIN conversations c ON c.id = t.convo_id
  WHERE t.term LIKE '% %' AND t.count >= 4
  GROUP BY t.term HAVING months >= 12
  ORDER BY months DESC, convos DESC LIMIT 15
`).all() as any[];

// 5. Core frameworks (from the convergence zone)
const frameworks = db.prepare(`
  SELECT c.title, c.created_at, c.total_words
  FROM convo_terms t
  JOIN conversations c ON c.id = t.convo_id
  WHERE t.term = 'codex vivus' AND c.score_tier = 'S'
  ORDER BY c.user_words DESC LIMIT 5
`).all() as any[];

// 6. Stats
const stats = db.prepare(`SELECT COUNT(*) as n, SUM(total_words) as w FROM conversations`).get() as any;
const dates = db.prepare(`SELECT MIN(created_at) as a, MAX(created_at) as b FROM conversations WHERE created_at > 0`).get() as any;
const tiers = db.prepare(`SELECT score_tier, COUNT(*) as n FROM conversations GROUP BY score_tier`).all() as any[];

// 7. Most recent conversations (last 2 weeks)
const latest = db.prepare(`
  SELECT title, created_at, category, score_tier, total_words, preview
  FROM conversations
  ORDER BY created_at DESC LIMIT 10
`).all() as any[];

// 8. Your biggest unfinished projects
const bigUnfinished = db.prepare(`
  SELECT title, created_at, total_words, user_words, category
  FROM conversations
  WHERE has_build = 1 AND score_tier = 'S' AND total_words > 20000
  AND created_at > unixepoch() - 365*86400
  ORDER BY user_words DESC LIMIT 8
`).all() as any[];

// Build the context document
let ctx = "";

ctx += `# OPERATOR CONTEXT — Justin Paul Åberg\n`;
ctx += `## Auto-generated by Codex Vivus from ${stats.n.toLocaleString()} conversations (${(stats.w/1e6).toFixed(1)}M words)\n`;
ctx += `## ${new Date(dates.a * 1000).toISOString().slice(0,10)} to ${new Date(dates.b * 1000).toISOString().slice(0,10)}\n\n`;

ctx += `## Who I Am\n\n`;
ctx += `Software engineer (7 years: Amazon, Disney, Capital One, DARPA/DoD autonomous systems). Based in Clark County, WA (Salmon Creek / Pacific Northwest / Columbia River region). Builder, systems thinker, political operative (WA State Bernie Delegate 2016, Democratic Central Committeeman CD3, launched Marie Gluesenkamp Perez's first campaign).\n\n`;
ctx += `My operating frequency is **sovereign**. I think in supply chains, power structures, feedback loops, and pattern recognition. I don't want summaries — I want leverage.\n\n`;

ctx += `## My Architecture (named systems I've built)\n\n`;
ctx += `| System | What it does | Depth |\n`;
ctx += `|--------|-------------|-------|\n`;
ctx += `| **Codex Vivus** | Living counter-system to institutional control. Knowledge graph + intelligence OS. | ${identity.find((i: any) => i.term === 'codex vivus')?.convos || '?'} convos |\n`;
ctx += `| **Iron Vein** | Supply chain intelligence. Collapse engineering. Substitution maps. | ${identity.find((i: any) => i.term === 'iron vein')?.convos || '?'} convos |\n`;
ctx += `| **Solis Memoria** | Persistent memory across AI sessions. The graph that remembers. | ${identity.find((i: any) => i.term === 'solis memoria')?.convos || '?'} convos |\n`;
ctx += `| **Codex Machina** | Model of the dominion system (legal, financial, narrative, digital control). | ${identity.find((i: any) => i.term === 'codex machina')?.convos || '?'} convos |\n`;
ctx += `| **Myth Tech** | Symbolic OS. Archetype engine. Makes structural truth legible. | ${identity.find((i: any) => i.term === 'myth tech')?.convos || '?'} convos |\n`;
ctx += `| **Promethea** | Sovereignty architecture. Myth-tech cognition system. | ${identity.find((i: any) => i.term === 'promethea')?.convos || '?'} convos |\n\n`;

ctx += `## Conversation Quality\n\n`;
for (const t of tiers) ctx += `- **${t.score_tier}**: ${t.n} conversations\n`;
ctx += `\n`;

ctx += `## Persistent Threads (topics I return to every month)\n\n`;
for (const t of threads) {
  ctx += `- **${(t as any).term}** — ${(t as any).months} months, ${(t as any).convos} convos\n`;
}
ctx += `\n`;

ctx += `## What I'm Building Right Now (last 90 days, S-tier)\n\n`;
for (const r of recentBuilds) {
  const d = new Date(r.created_at * 1000).toISOString().slice(0, 10);
  ctx += `- ${d} — **${r.title}** (${r.category}, ${(r.total_words/1000).toFixed(0)}K words)\n`;
}
ctx += `\n`;

ctx += `## Open Decisions (last 60 days)\n\n`;
for (const r of recentDecisions) {
  const d = new Date(r.created_at * 1000).toISOString().slice(0, 10);
  ctx += `- ${d} — **${r.title}** (${r.category})\n`;
}
ctx += `\n`;

ctx += `## Most Recent Conversations\n\n`;
for (const r of latest) {
  const d = new Date(r.created_at * 1000).toISOString().slice(0, 10);
  ctx += `- ${d} ${r.score_tier} ${r.category.padEnd(10)} **${r.title}**\n`;
}
ctx += `\n`;

ctx += `## Biggest Active Projects (past year, S-tier, 20K+ words)\n\n`;
for (const r of bigUnfinished) {
  const d = new Date(r.created_at * 1000).toISOString().slice(0, 10);
  const you = Math.round(r.user_words / r.total_words * 100);
  ctx += `- ${d} — **${r.title}** (${(r.total_words/1000).toFixed(0)}K words, ${you}% you)\n`;
}
ctx += `\n`;

ctx += `## How to Work With Me\n\n`;
ctx += `- No filler. Cognitive density. Every sentence carries signal.\n`;
ctx += `- Think in systems, not features. Show upstream causes and downstream consequences.\n`;
ctx += `- I already know the basics — go deep, not wide.\n`;
ctx += `- When I say "plain english" I mean ELI5 but structurally precise.\n`;
ctx += `- Reference my existing systems (Codex Vivus, Iron Vein, etc.) when relevant — don't reinvent what I've already built.\n`;
ctx += `- I have a working Codex Vivus CLI that can search all ${stats.n.toLocaleString()} conversations. If I need to look something up, I can.\n`;

// Write outputs
const contextPath = "/Users/ltlai/codex-vivus/OPERATOR_CONTEXT.md";
fs.writeFileSync(contextPath, ctx);

// Also write a CLAUDE.md for the home directory
const claudePath = "/Users/ltlai/CLAUDE.md";
let claude = `# Operator: Justin Paul Åberg\n\n`;
claude += `This machine has a Codex Vivus knowledge graph at \`~/.codex-vivus/graph.db\` containing ${stats.n.toLocaleString()} indexed AI conversations (${(stats.w/1e6).toFixed(1)}M words, ${new Date(dates.a * 1000).toISOString().slice(0,10)} to ${new Date(dates.b * 1000).toISOString().slice(0,10)}).\n\n`;
claude += `Query it: \`cd ~/codex-vivus && npx tsx src/cli.ts search "topic"\`\n\n`;
claude += `Full operator context: \`cat ~/codex-vivus/OPERATOR_CONTEXT.md\`\n\n`;
claude += `## Key Systems\n\n`;
claude += `- **Codex Vivus** (~/codex-vivus/) — Living intelligence OS. SQLite graph + FTS5 search.\n`;
claude += `- **Imprint** (~/imprint/) — AI conversation visualizer. Next.js web app + Python analysis.\n`;
claude += `- **Infinite Intelligence** (~/infinite-intelligence/) — Prompt architecture & cognitive OS specs.\n\n`;
claude += `## Preferences\n\n`;
claude += `- No filler. Cognitive density. Lead with the answer.\n`;
claude += `- Think in systems. Show leverage points.\n`;
claude += `- Reference existing work before proposing new abstractions.\n`;
claude += `- When touching Imprint: don't modify without explicit permission.\n`;

fs.writeFileSync(claudePath, claude);

console.log(`Written:`);
console.log(`  ${contextPath} (${ctx.split('\n').length} lines — full operator context)`);
console.log(`  ${claudePath} (home CLAUDE.md — auto-loaded by Claude Code)`);
console.log(`\nEvery new Claude Code session on this machine now knows who you are.`);

db.close();
